apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: pg-iec104
    access: proxy
    url: postgres:5432
    database: iec104
    user: iec104
    secureJsonData:
      password: iec104
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
